version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./src:/backend/src
